-- Create Profiles Table (Linked to Auth)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  name text,
  role text check (role in ('vet', 'client')),
  address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Pets Table
create table pets (
  id bigint generated by default as identity primary key,
  owner_id uuid references profiles(id) on delete cascade not null,
  name text not null,
  type text,
  breed text,
  age text,
  weight text,
  chip_id text,
  owner_name text,
  image text,
  last_checkup text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Appointments Table
create table appointments (
  id bigint generated by default as identity primary key,
  owner_id uuid references profiles(id) on delete cascade not null,
  owner_name text,
  owner_rut text,
  pet_name text,
  description text,
  address text,
  status text default 'pending',
  paid boolean default false,
  date timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table pets enable row level security;
alter table appointments enable row level security;

-- Policies (Simple for MVP)
-- Profiles: Users can read/update their own profile. Vets can read all profiles (simplified).
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

-- Pets: Owners can see their pets. Vets can see all pets.
create policy "Owners view own pets" on pets for select using (auth.uid() = owner_id);
create policy "Vets view all pets" on pets for select using (exists (select 1 from profiles where id = auth.uid() and role = 'vet'));
create policy "Owners insert pets" on pets for insert with check (auth.uid() = owner_id);
create policy "Vets insert pets" on pets for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'vet'));

-- Appointments: Similar logic
create policy "Owners view own appointments" on appointments for select using (auth.uid() = owner_id);
create policy "Vets view all appointments" on appointments for select using (exists (select 1 from profiles where id = auth.uid() and role = 'vet'));
create policy "Owners insert appointments" on appointments for insert with check (auth.uid() = owner_id);
create policy "Vets update appointments" on appointments for update using (exists (select 1 from profiles where id = auth.uid() and role = 'vet'));
